[package]
name = "mission_scanner"
version = "0.1.0"
edition = "2024"

[dependencies]
pbo_tools = { path = "../pbo_tools" }
cpp_parser = { path = "../cpp_parser" }
sqm_parser = { path = "../sqm_parser" }
sqf_parser = { path = "../sqf_parser" }
clap = { version = "4.5.31", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }
futures = "0.3.31"
walkdir = "2.5.0"
log = "0.4.26"
env_logger = "0.11.6"
log4rs = { version = "1.3.0", features = ["file_appender", "pattern_encoder", "yaml_format"] }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
serde_yaml = "0.9.33"
toml = "0.8.12"
sha2 = "0.10.8"
anyhow = "1.0.96"
rayon = "1.8.0"
indicatif = { version = "0.17.11", features = ["rayon"] }
chrono = { version = "0.4.35", features = ["serde"] }
once_cell = "1.19.0"
num_cpus = "1.16.0"

[dev-dependencies]
test-case = "3.3.1"
pretty_assertions = "1.4.1"
tempfile = "3.8.1"

[lints.rust]
dead_code = "allow"
unused_parens = "allow"
unused_imports = "allow"
unused_variables = "allow"
unused_mut = "allow"
