[package]
name = "parser_sqf"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "parser_sqf"
path = "src/main.rs"

[dependencies]
chumsky = "0.9.3"
ariadne = "0.5.0" # For error reporting
thiserror = "2.0.12" # For error handling

[lints.rust]
dead_code = "allow"
unused_variables = "allow"
unused_imports = "allow"
unused_assignments = "allow"
