[package]
name = "parser_sqf"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
hemtt-sqf = { git = "https://github.com/BrettMayson/HEMTT.git", tag = "v1.14.6" }
hemtt-workspace = { git = "https://github.com/BrettMayson/HEMTT.git", tag = "v1.14.6" }
hemtt-preprocessor = { git = "https://github.com/BrettMayson/HEMTT.git", tag = "v1.14.6" }
hemtt-common = { git = "https://github.com/BrettMayson/HEMTT.git", tag = "v1.14.6" }

[dev-dependencies]
tempfile = "3.8.1"

[lints.rust]
dead_code = "allow"
unused_variables = "allow"
unused_imports = "allow"
unused_assignments = "allow"