[package]
name = "parser_sqf"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
hemtt-sqf = { git = "https://github.com/BrettMayson/HEMTT", rev = "0bdf5e7" }
hemtt-workspace = { git = "https://github.com/BrettMayson/HEMTT", rev = "0bdf5e7" }
hemtt-preprocessor = { git = "https://github.com/BrettMayson/HEMTT", rev = "0bdf5e7" }
hemtt-common = { git = "https://github.com/BrettMayson/HEMTT", rev = "0bdf5e7" }
codespan-reporting = { version = "0.11.1", features = ["serialization"] }
thiserror = "2.0.12"

[dev-dependencies]
tempfile = "3.18.0"

[lints.rust]
dead_code = "allow"
unused_variables = "allow"
unused_imports = "allow"
unused_assignments = "allow"