[package]
name = "parser_sqf"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.218", features = ["derive"] }
thiserror = "2.0.12"
nom = "7.1.3"
hash32 = "0.3.1"

[dev-dependencies]
pretty_assertions = "1.4.0"